version: '3'
services:
  openresty_1_13:
    image: openresty/openresty:1.13.6.2-2-bionic
    container_name: openresty-1.13
    ports:
      - "8080:80"
    volumes:
      - ./web/data:/data
      - ./default.conf:/etc/nginx/conf.d/default.conf
  openresty_latest:
    image: openresty/openresty:latest
    container_name: openresty-latest
    ports:
      - "8085:80"
    volumes:
      - ./web/data:/data
      - ./default.conf:/etc/nginx/conf.d/default.conf      
